### ISSUE TITLE
running next build and lamba function in same project

### ISSUE THREAD

**Issue by thomas159** [netlify/next-on-netlify#73]
I have a netlify-lambda function that generates an api.js file into out_functions and then I run the next build and this erases the contents of the out_functions folder removing my api.s file and populates it with the nextjs functions. Is there anyway to change the folder directory or another way around this to  prevent it overwriting my other file?

**Comment by FinnWoelm** [comment]
Hi @thomas159, 

Great to hear from you! Welcome to `next-on-netlify` 👋

You are referring to the `out_functions` folder? That's the folder where `next-on-netlify` creates its functions. (`out_publish` is for the static assets and pre-rendered pages).

Currently there is no built-in way to add custom functions to the ones generated by `next-on-netlify`. What you can do is to copy your `api.js` file to `out_functions` **after** you run `next-on-netlify`.

For example, your Netlify command in your `netlify.toml` could be:

```toml
[build]
  command   = "npm run build && cp ./my_functions/api.js ./out_functions/api.js"
  functions = "out_functions"
  publish   = "out_publish"
```

Does that help? Don't hesitate to let us know if you run into any issues! More than happy to help!
Finn
