### ISSUE TITLE
Request: allow `out_functions`/`out_publish` directory names to be configurable

### ISSUE THREAD

**Issue by ChrisBAshton** [netlify/next-on-netlify#81]
I spent quite some time editing my `netlify.toml`, trying to consolidate the outputs into one folder with subfolders, i.e.:

```toml
[build]
  command = "npm run build"
  functions = "out/functions"
  publish = "out/publish"
```

I ran `npm run build` and was confused that it would still output to `out_functions` and `out_publish` folders. Then I realised [these are hard-coded](https://github.com/netlify/next-on-netlify/blob/1f1373eacc3d5ba8b5f1c44334516b5aa3588573/lib/config.js#L6-L10) and cannot be configured.

Could we make this configurable? If not, could we make it clearer in the README that these are fixed directory names?
